wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.8
    start_time: 1670291854.95916
    t:
      1:
      - 1
      - 41
      - 49
      - 55
      - 63
      2:
      - 1
      - 41
      - 49
      - 55
      - 63
      3:
      - 16
      - 23
      - 37
      4: 3.10.8
      5: 0.13.5
      8:
      - 5
batch_size:
  desc: null
  value: 100
clip_grad_norm:
  desc: null
  value: 10
cov_update_freq:
  desc: null
  value: 10
damping:
  desc: null
  value: 0.001
data_path:
  desc: null
  value: /home/lfsm/sundatasets/CIFAR100
dataset:
  desc: null
  value: CIFAR100
device:
  desc: null
  value: cuda
ema_decay:
  desc: null
  value: -1
epochs:
  desc: null
  value: 40
img_size:
  desc: null
  value: 224
inv_update_freq:
  desc: null
  value: 100
label_smoothing:
  desc: null
  value: 0.1
log_interval:
  desc: null
  value: 100
lr:
  desc: null
  value: 0.0003
model:
  desc: null
  value: resnet18
momentum:
  desc: null
  value: 0.9
num_workers:
  desc: null
  value: 4
optimizer:
  desc: null
  value: sgd
pretrained:
  desc: null
  value: true
seed:
  desc: null
  value: 1
warmup_epochs:
  desc: null
  value: 0
warmup_factor:
  desc: null
  value: 0.1
weight_decay:
  desc: null
  value: 0.0001
